name: pyramid_clamav tests

on:
  push:
  pull_request:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 3 * * *'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout pyramid_clamav
      uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
          pip install -e .
          pip install -e .[test]
    - name: Test with pytest
      run: pytest
      env:
        PYTHONUNBUFFERED: 1
        CI: 1
