name: pyramid_clamav tests

on:
  push:
  pull_request:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 3 * * *'


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.7]

    steps:
    - name: Checkout pyramid_clamav
      uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
          pip install -e .
          pip install -e .[test]
    - name: Test with pytest
      run: pytest
      env:
        PYTHONUNBUFFERED: 1
